import fs from 'node:fs';
import {composeEditorial} from './composition.mjs';
const source=fs.readFileSync(new URL('./source-content.txt',import.meta.url),'utf8').replace(/\r/g,'');
const sections={}; for(const m of source.matchAll(/БЛОК (\d+)\.[^\n]*\n([\s\S]*?)(?=БЛОК \d+\.|$)/g)) sections[+m[1]]=m[2].trim();
sections[13]=sections[13].split('Да, давай')[0].trim();
const esc=s=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const lines=s=>s.split('\n').map(x=>x.trim()).filter(Boolean);
const rich=s=>lines(s).map(l=>/^—/.test(l)?`<p class="bullet">${esc(l.slice(1).trim())}</p>`: l===l.toUpperCase()&&/[А-Я]/.test(l)?`<h4>${esc(l)}</h4>`:`<p>${esc(l)}</p>`).join('');
const numbered=s=>[...s.matchAll(/(?:^|\n)(\d{2})\. ([^\n]+)\n([\s\S]*?)(?=\n\d{2}\. |$)/g)].map(m=>({n:m[1],title:m[2],body:m[3].trim()}));
const cap=(n,t)=>`<div class="section-label"><span>${n}</span> ${t}</div>`;
const cta=(label='Присоединиться к CREATOR',href='#formats')=>`<a class="button" href="${href}"><span>${label}</span><span aria-hidden="true">↗</span></a>`;
const details=(n,t,b)=>`<details><summary><span class="index">${n}</span><span>${esc(t)}</span><span class="plus" aria-hidden="true">+</span></summary><div class="detail-body">${rich(b)}</div></details>`;
const moduleText=sections[9].split('И В КОНЦЕ ВСЕЙ ПРОГРАММЫ')[0];
const modules=numbered(moduleText);
const concepts=numbered(sections[2]);
const problems=lines(sections[3]).filter(l=>l.startsWith('«'));
const tasks=[...sections[4].matchAll(/ЗАДАЧА (\d+)\n([^\n]+)\nЧто делаем:\n([^\n]+)\nРезультат:\n([^\n]+)/g)];
const audience=numbered(sections[8]);
const faq=[...sections[16].matchAll(/(?:^|\n)([^\n]+\?)\n([\s\S]*?)(?=\n[^\n]+\?\n|$)/g)];
const expert=(name,img,body,market)=>`<article class="expert"><div class="portrait"><img src="assets/${img}" alt="${name}" loading="lazy" width="600" height="700"><span class="market">${market}</span></div><div class="expert-copy"><h3>${name}</h3>${rich(lines(body).slice(1,3).join('\n'))}<details><summary>Опыт и темы в CREATOR <span class="plus" aria-hidden="true">+</span></summary><div class="detail-body">${rich(lines(body).slice(3).join('\n'))}</div></details></div></article>`;
const experts=sections[7].split('\nТИХОН БЕЛЯЕВ\n');
const plans=['CREATOR','CREATOR PRO','CREATOR VIP'].map((name,i)=>{
const start=sections[14].indexOf('\n'+name+'\n')+name.length+2;
const end=i<2?sections[14].indexOf('\n'+['CREATOR PRO','CREATOR VIP'][i]+'\n'):sections[14].indexOf('\nНе знаете');
const body=sections[14].slice(start,end);const bl=lines(body);const list=bl.filter(l=>l.startsWith('—'));
return `<article class="plan ${i===1?'featured':''}"><div class="plan-top"><span>${i===0?'Основная программа':i===1?'С ментором':'С Лерой и Тихоном'}</span>${i?`<span>${i===1?'50':'10'} мест</span>`:''}</div><h3>${name}</h3><p class="plan-intro">${esc(bl[0])}</p><p>${esc(bl[1])}</p><div class="price">Стоимость уточняется</div><button class="button" type="button" data-plan="${name}"><span>Выбрать ${name}</span><span aria-hidden="true">↗</span></button><p class="included">${i===0?'В программе:':i===1?'Всё из CREATOR, а также:':'Всё из CREATOR PRO, а также:'}</p><ul>${list.map(l=>`<li>${esc(l.slice(1))}</li>`).join('')}</ul>${bl.filter(l=>l.startsWith('Результат тарифа:')).map(l=>`<p class="plan-result">${esc(l)}</p>`).join('')}</article>`;
}).join('');
const cardsFromPairs=(s,start=2)=>{let a=lines(s).slice(start);let out=[];for(let i=0;i<a.length;i+=2)out.push(`<article class="text-card"><h3>${esc(a[i])}</h3><p>${esc(a[i+1]||'')}</p></article>`);return out.join('')};
const html=`<!doctype html><html lang="ru"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#52141f"><title>CREATOR — Лера Рума × Тихон Беляев</title><meta name="description" content="Практическая программа для бьюти-предпринимателей: 6 недель, 8 блоков, живая работа с Лерой Румой и Тихоном Беляевым. Опыт Украины и Европы."><link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='16' fill='%2352141f'/%3E%3Ctext x='32' y='47' text-anchor='middle' font-family='Georgia' font-size='47' fill='%23ecd9b5'%3EC%3C/text%3E%3C/svg%3E"><link rel="preload" href="assets/creator.ttf" as="font" type="font/ttf" crossorigin><link rel="preload" href="assets/hero-duo-extended.jpg" as="image"><link rel="stylesheet" href="style.css"><script src="app.js" defer></script></head><body><a class="skip" href="#main">Перейти к содержанию</a>
<header><a class="brand" href="#home" aria-label="CREATOR — начало">CREATOR<span>by Рума × Беляев</span></a><nav aria-label="Основная навигация"><a href="#about">О программе</a><a href="#mentors">Менторы</a><a href="#program">Программа</a><a href="#formats">Форматы</a></nav><a class="nav-cta" href="#formats">Присоединиться <span aria-hidden="true">↗</span></a><button class="menu-toggle" aria-expanded="false" aria-controls="mobile-nav" aria-label="Открыть меню">☰</button><nav id="mobile-nav" aria-label="Мобильная навигация" hidden><a href="#about">О программе</a><a href="#mentors">Менторы</a><a href="#program">Программа</a><a href="#formats">Форматы участия</a><a href="#faq">Вопросы</a></nav></header>
<main id="main"><section class="hero" id="home"><div class="hero-top"><span>Практическая программа для бьюти-предпринимателей</span><span>ONLINE / 6 НЕДЕЛЬ</span></div><h1>CREATOR</h1><div class="hero-grid"><div class="hero-copy"><p class="eyebrow">Лера Рума × Тихон Беляев</p><h2>Ваш бизнес.<br>Новая <em>система</em><br>роста.</h2><p>От точки, в которой ваш бизнес находится сейчас, до точки, в которой он растёт системно: с сильной командой, работающим маркетингом, выстроенной финансовой моделью и чётким планом развития.</p>${cta()}<p class="start">Старт программы — дата уточняется</p></div><figure class="hero-visual"><img src="assets/hero-duo-extended.jpg" alt="Менторы CREATOR — Лера Рума и Тихон Беляев" width="900" height="1350" fetchpriority="high"><figcaption><span>Два предпринимателя.<br>Два рынка. Одна индустрия.</span><span class="seal">C<span>CREATOR</span></span></figcaption></figure></div><div class="hero-bottom"><span>УКРАИНА × ЕВРОПА</span><span>Знания, которые становятся действиями</span><a href="#about" aria-label="Подробнее о программе">↓</a></div></section>
<div class="ticker" aria-hidden="true">ФИНАНСЫ <span>✦</span> МАРКЕТИНГ <span>✦</span> КОМАНДА <span>✦</span> УПРАВЛЕНИЕ <span>✦</span> РОСТ</div>
<section class="section" id="about">${cap('01','БОЛЬШЕ, ЧЕМ ОБУЧЕНИЕ')}<div class="split-heading"><h2>Не просто знания.<br><em>Работа с вашим бизнесом.</em></h2><p>Комбинация методологии, практических инструментов и наставничества двух предпринимателей, которые развивают бьюти-бизнес на рынках Европы и Украины.</p></div><div class="concepts">${concepts.map(c=>`<article><span class="big-number">${c.n}</span><h3>${esc(c.title)}</h3><p>${esc(c.body.split('\nНЕ «')[0])}</p></article>`).join('')}</div><details class="more"><summary>Как вы будете работать в CREATOR <span class="plus" aria-hidden="true">+</span></summary><div class="detail-body">${rich(sections[2].slice(sections[2].indexOf('В CREATOR'),sections[2].indexOf('01.')))}</div></details></section>
<section class="section wine" id="requests">${cap('02','ВАША ТОЧКА СЕЙЧАС')}<h2>Знакомо?<br><em>С этого начинается рост.</em></h2><div class="quotes">${problems.map((p,i)=>`<blockquote><span>${String(i+1).padStart(2,'0')}</span><p>${esc(p)}</p></blockquote>`).join('')}</div><p class="closing-line">CREATOR начинается с понимания вашей текущей точки и реальных задач бизнеса.</p></section>
<section class="section">${cap('03','ЗАДАЧИ ПРОГРАММЫ')}<h2>От отдельных проблем —<br><em>к целостной системе.</em></h2><div class="task-grid">${tasks.map(m=>`<article class="task"><span class="index">${m[1]}</span><h3>${esc(m[2])}</h3><p>${esc(m[3])}</p><div class="result"><span>Результат</span><p>${esc(m[4])}</p></div></article>`).join('')}</div></section>
<section class="section dark method">${cap('04','ЖИВОЙ ФОРМАТ')}<h2>Не отложить на потом.<br><em>Внедрить сейчас.</em></h2><p>Здесь не будет десятков записанных уроков, которые вы обещаете себе когда-нибудь посмотреть. CREATOR построен как живая практическая программа, где информация сразу соединяется с работой над вашим проектом.</p><div class="flow">${['Видеоподкасты','Задания','Живые сессии','Разборы','Обратная связь','Внедрение'].map((x,i)=>`<span><small>0${i+1}</small>${x}</span>`).join('')}</div></section>
<section class="section" id="mentors">${cap('05','ВАШИ МЕНТОРЫ')}<div class="split-heading"><h2>Два опыта.<br><em>Больше возможностей.</em></h2><p>Лера и Тихон работают с командами, клиентами, маркетингом, финансами и управлением в разных странах и разных условиях. В CREATOR вы смотрите на бизнес с двух сторон и собираете собственную работающую систему.</p></div><div class="experts">${expert('Лера Рума','lera-avatar.png',experts[0].replace('ЛЕРА РУМА\n',''),'ЕВРОПА / KRASIVO PROJECT')}${expert('Тихон Беляев','tikhon-belyaev-portrait.jpg',experts[1],'УКРАИНА / YEEZY')}</div></section>
<section class="section audience">${cap('06','ДЛЯ КОГО CREATOR')}<h2>Ваша следующая глава<br><em>начинается здесь.</em></h2><div class="audience-grid">${audience.map(a=>`<article><span class="index">${a.n}</span><h3>${esc(a.title)}</h3><p>${esc(a.body.split('\nНеважно')[0])}</p></article>`).join('')}</div><p class="closing-line">Работаете самостоятельно, управляете командой или развиваете большой проект — каждый работает со своей текущей точкой.</p></section>
<section class="section program" id="program">${cap('07','ПРОГРАММА CREATOR')}<div class="split-heading"><h2><span class="huge">8</span> блоков.<br><em>Одна система.</em></h2><p>Бизнес → финансы → команда → сервис → клиентская база → маркетинг → личный бренд → дальнейший рост.<br><br>В каждом блоке: видеоподкаст, практическая работа, материалы, онлайн-мастермайнд, вопросы и внедрение.</p></div><div class="modules">${modules.map(m=>details(m.n,m.title,m.body)).join('')}</div><div class="program-note"><span>ЗНАНИЯ + ИНСТРУМЕНТЫ + ПРАКТИКА</span><p>К финалу у вас собрана рабочая база по собственному проекту: диагностика, расчёты, таблицы, решения, маркетинговый план, задачи по команде и план дальнейшего развития.</p></div></section>
<section class="section wine">${cap('08','КАК ПРОХОДИТ CREATOR')}<h2>Смотрите. Разбираете.<br><em>Меняете свой бизнес.</em></h2><div class="steps">${numbered(sections[10]).map(s=>`<article><span class="big-number">${s.n}</span><div><h3>${esc(s.title)}</h3><p>${esc(s.body)}</p></div></article>`).join('')}</div></section>
<section class="section">${cap('09','ЧТО ВНУТРИ')}<h2>Всё для работы<br><em>над вашим проектом.</em></h2><div class="included-grid">${cardsFromPairs(sections[11])}</div></section>
<section class="section case-section"><div>${cap('10','РЕАЛЬНЫЕ ПРОЕКТЫ')}<h2>Ваш бизнес —<br><em>в центре работы.</em></h2><p>На протяжении CREATOR мы берём реальные проекты и ситуации участников и разбираем их вместе на онлайн-встречах.</p><div class="case-flow">Исходная ситуация → основная проблема → вопросы → возможные решения → следующие действия</div></div><div class="case-list">${rich(sections[12].slice(sections[12].indexOf('Это может быть:'),sections[12].indexOf('КАК ПРОХОДИТ РАЗБОР')))}<p>Даже если разбирают не ваш проект, вы находите решения, актуальные для своего бизнеса.</p></div></section>
<section class="section">${cap('11','ВАШ РЕЗУЛЬТАТ')}<h2>Не только новые знания.<br><em>Понятный следующий шаг.</em></h2><div class="outcomes">${cardsFromPairs(sections[13].split('ВЫ ВЫЙДЕТЕ ИЗ CREATOR С ПОНИМАНИЕМ:')[0],3)}</div><div class="result-strip">Где бизнес сейчас <span>→</span> Что мешает расти <span>→</span> Какие решения нужны <span>→</span> Что делать дальше</div></section>
<section class="section formats" id="formats">${cap('12','ФОРМАТЫ УЧАСТИЯ')}<h2>Одна программа.<br><em>Ваша глубина работы.</em></h2><p class="intro">Основная программа и еженедельные мастермайнды — во всех форматах. Разница — в глубине обратной связи, количестве разборов и персональной работе с вашим проектом.</p><div class="plans">${plans}</div><div class="consult"><div><h3>Не знаете, какой формат выбрать?</h3><p>Команда CREATOR поможет подобрать вариант под вашу текущую точку и задачи.</p></div><button class="button" data-plan="Консультация">Получить консультацию <span aria-hidden="true">↗</span></button></div></section>
<section class="section">${cap('13','ПОСЛЕ РЕГИСТРАЦИИ')}<h2>Вы в CREATOR.<br><em>Что дальше?</em></h2><div class="onboarding">${numbered(sections[15]).map(x=>`<article><span class="index">${x.n}</span><h3>${esc(x.title)}</h3><p>${esc(x.body.split('\nОт первого дня')[0])}</p></article>`).join('')}</div></section>
<section class="section faq" id="faq">${cap('14','ЧАСТЫЕ ВОПРОСЫ')}<div class="faq-layout"><h2>Осталось<br><em>разобраться<br>в деталях.</em></h2><div>${faq.map((m,i)=>details('',m[1],m[2])).join('')}</div></div></section>
<section class="section final-cta"><p class="eyebrow">Лера Рума × Тихон Беляев</p><h2>CREATOR</h2><p>Сильный бьюти-бизнес строится из системы.<br>Начните собирать свою.</p><div class="final-meta"><span>6 недель</span><span>Online</span><span>Украина × Европа</span></div>${cta('Выбрать формат участия')}<p class="start">Дата старта уточняется</p></section></main>
<footer><a class="brand" href="#home">CREATOR</a><p>Практическая программа для бьюти-предпринимателей</p><a href="#home">Наверх ↑</a></footer><dialog id="enrollment" aria-labelledby="dialog-title"><button class="dialog-close" aria-label="Закрыть окно">×</button><p class="eyebrow">Формат участия</p><h2 id="dialog-title">CREATOR</h2><p>Дата старта и стоимость участия уточняются.</p><p>Регистрация на этот формат пока не открыта. Информация о записи появится здесь.</p><button class="button dialog-back">Вернуться к форматам <span aria-hidden="true">↗</span></button></dialog></body></html>`;
let polished=html.replace('<link rel="stylesheet" href="style.css">','<link rel="stylesheet" href="style.css"><link rel="stylesheet" href="visual.css">');
polished=polished.replace('</em><br>роста.','</em> <br>роста.');
polished=polished.replace('<link rel="preload" href="assets/hero-duo-extended.jpg" as="image">','<link rel="preload" href="assets/hero-cinematic.png" as="image">');
polished=polished.replace('<body>','<body><div class="reading-progress" aria-hidden="true"></div>');
polished=polished.replace('<div class="hero-top">','<div class="hero-stage" aria-hidden="true"><img src="assets/hero-cinematic.png" alt="" width="1536" height="1024"></div><div class="hero-top">');
polished=polished.replace('<figure class="hero-visual">','<figure class="hero-visual"><div class="floating-note note-one"><b>6</b><span>недель<br>на новый уровень</span></div><div class="floating-note note-two"><span>Украина</span><b>×</b><span>Европа</span></div>');
polished=polished.replace('<div class="ticker" aria-hidden="true">ФИНАНСЫ <span>✦</span> МАРКЕТИНГ <span>✦</span> КОМАНДА <span>✦</span> УПРАВЛЕНИЕ <span>✦</span> РОСТ</div>',`<div class="ticker" aria-hidden="true"><div class="ticker-track">${Array.from({length:4},()=>'<span>ФИНАНСЫ <i>✦</i> МАРКЕТИНГ <i>✦</i> КОМАНДА <i>✦</i> УПРАВЛЕНИЕ <i>✦</i> РОСТ <i>✦</i></span>').join('')}</div></div>`);
polished=polished.replace('<section class="section dark method">',`<section class="section dark method"><div class="photo-ribbon"><figure class="ribbon-photo photo-a"><img src="assets/lera-stage-talk.png" alt="Лера Рума выступает на бизнес-конференции" width="331" height="213" loading="lazy"><figcaption>ОПЫТ, КОТОРЫМ ДЕЛЯТСЯ</figcaption></figure><figure class="ribbon-photo photo-b"><img src="assets/lera-event-audience.png" alt="Участники бизнес-конференции" width="526" height="213" loading="lazy"><figcaption>ЛЮДИ. ИДЕИ. РОСТ.</figcaption></figure><figure class="ribbon-photo photo-c"><img src="assets/lera-live-event.png" alt="Живая атмосфера выступления Леры" width="331" height="213" loading="lazy"><figcaption>ЖИВАЯ ЭНЕРГИЯ БИЗНЕСА</figcaption></figure></div>`);
polished=polished.replace('<div class="modules">',`<div class="program-layout"><aside class="program-art"><img src="assets/speaker-finance-event.jpg" alt="Лера Рума делится предпринимательским опытом со сцены" width="1200" height="1064" loading="lazy"><div class="program-art-copy"><span>ОТ ОПЫТА — К ВАШЕЙ СИСТЕМЕ</span><b>8</b><p>точек опоры<br>для вашего бизнеса</p></div></aside><div class="modules">`);
polished=polished.replace('<div class="program-note">','</div><div class="program-note">');
polished=polished.replace('<div class="outcomes">','<div class="outcomes"><div class="outcome-statement"><span>ВАША НОВАЯ ТОЧКА</span><strong>Из хаоса<br>в <em>систему.</em></strong><span class="statement-arrow" aria-hidden="true">↗</span></div>');
polished=polished.replace('<footer>','<footer><button class="motion-toggle" type="button" aria-pressed="false">Пауза анимации</button>');
fs.writeFileSync(new URL('./dist/index.html',import.meta.url),composeEditorial(polished));
console.log(JSON.stringify({sections:Object.keys(sections).length,modules:modules.length,faq:faq.length,tasks:tasks.length,plans:3}));
